# Generated by Django 6.0.5 on 2026-05-27 10:17

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(editable=False, help_text='Unique return reference number (e.g., RET-20241215-0001)', max_length=50, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Sent'), ('changed_mind', 'Changed Mind / No Longer Needed'), ('expired', 'Expired Product'), ('damaged', 'Damaged During Delivery'), ('incorrect_quantity', 'Incorrect Quantity'), ('poor_quality', 'Poor Quality'), ('better_price', 'Found Better Price Elsewhere'), ('not_as_described', 'Not as Described'), ('other', 'Other Reason')], max_length=30)),
                ('reason_description', models.TextField(blank=True, help_text='Additional details about the return')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Ready for Refund'), ('rejected', 'Rejected'), ('completed', 'Completed - Refund Issued'), ('cancelled', 'Cancelled by Customer')], db_index=True, default='pending', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total refund amount before fees', max_digits=12)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Restocking fee (if applicable)', max_digits=12)),
                ('shipping_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refund for shipping cost', max_digits=12)),
                ('net_refund', models.DecimalField(decimal_places=2, editable=False, help_text='Final refund amount = refund_amount - restocking_fee + shipping_refund', max_digits=12)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash Refund'), ('mpesa', 'M-Pesa Refund'), ('bank_transfer', 'Bank Transfer'), ('store_credit', 'Store Credit'), ('loyalty_points', 'Loyalty Points Refund'), ('original_payment', 'Original Payment Method')], default='original_payment', max_length=20)),
                ('mpesa_phone', models.CharField(blank=True, help_text='Phone number for M-Pesa refund', max_length=15)),
                ('mpesa_refund_code', models.CharField(blank=True, help_text='M-Pesa refund transaction code', max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('bank_reference', models.CharField(blank=True, max_length=100)),
                ('store_credit_code', models.CharField(blank=True, help_text='Generated store credit code', max_length=50)),
                ('store_credit_expiry', models.DateField(blank=True, null=True)),
                ('restock_items', models.BooleanField(default=True, help_text='Return items to inventory?')),
                ('item_condition', models.CharField(choices=[('new', 'New/Unused'), ('like_new', 'Like New - Original Packaging'), ('good', 'Good - Light Use'), ('fair', 'Fair - Visible Wear'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('customer_notes', models.TextField(blank=True, help_text='Notes from customer')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if return is rejected')),
                ('return_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Refund amount for this item', max_digits=12)),
                ('item_reason', models.CharField(blank=True, max_length=200)),
                ('condition', models.CharField(blank=True, help_text='Condition of the returned item', max_length=50)),
                ('restock', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Return Created'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('processed', 'Refund Processed'), ('cancelled', 'Return Cancelled'), ('note_added', 'Note Added')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('data_snapshot', models.JSONField(default=dict, help_text='Store relevant data at action time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
