# Generated by Django 6.0.5 on 2026-05-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_message_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_app', 'In-App Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Channel-specific settings')),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_hour', models.IntegerField(default=1000)),
                ('rate_limit_per_day', models.IntegerField(default=10000)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('channel_response', models.JSONField(default=dict)),
                ('error_details', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('high_value_sale', 'High Value Sale'), ('sale_completed', 'Sale Completed'), ('return_requested', 'Return Requested'), ('refund_processed', 'Refund Processed'), ('customer_registered', 'Customer Registered'), ('daily_summary', 'Daily Summary'), ('weekly_report', 'Weekly Report'), ('system_error', 'System Error')], max_length=30)),
                ('conditions', models.JSONField(default=dict, help_text='Conditions to trigger notification')),
                ('recipient_roles', models.JSONField(default=list, help_text='Roles to notify (admin, manager, cashier)')),
                ('additional_recipients', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('delay_minutes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('throttle_per_hour', models.IntegerField(default=10, help_text='Max notifications per hour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('sale', 'Sale Notification'), ('return', 'Return Request'), ('refund', 'Refund Processed'), ('payment', 'Payment Received'), ('customer_welcome', 'Customer Welcome'), ('customer_birthday', 'Customer Birthday'), ('daily_summary', 'Daily Sales Summary'), ('weekly_report', 'Weekly Report'), ('system_alert', 'System Alert')], max_length=30)),
                ('subject_template', models.CharField(help_text='Email subject or SMS title', max_length=200)),
                ('body_template', models.TextField(help_text='Template body with {{ variables }}')),
                ('html_template', models.TextField(blank=True, help_text='HTML version for email')),
                ('available_variables', models.JSONField(default=list, help_text='List of available variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
