# Generated by Django 6.0.5 on 2026-05-27 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('returns', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='customer',
            field=models.ForeignKey(help_text='Customer returning the product', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='return',
            name='original_sale',
            field=models.ForeignKey(help_text='Original sale being returned', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='return',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff who issued the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='requested_by',
            field=models.ForeignKey(help_text='Staff member who processed the return request', on_delete=django.db.models.deletion.PROTECT, related_name='returns_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnimage',
            name='return_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='returns.return'),
        ),
        migrations.AddField(
            model_name='returnimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='original_sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return'),
        ),
        migrations.AddField(
            model_name='returnlog',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnlog',
            name='return_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='returns.return'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_number'], name='returns_ret_return__576d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['original_sale'], name='returns_ret_origina_946ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer', 'status'], name='returns_ret_custome_8a7a84_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_date'], name='returns_ret_return__21e049_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status', 'return_date'], name='returns_ret_status_9d4a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_obj', 'product'], name='returns_ret_return__f83f71_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['original_sale_item'], name='returns_ret_origina_1c2b8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='returnitem',
            unique_together={('return_obj', 'original_sale_item')},
        ),
    ]
