# Generated by Django 6.0.5 on 2026-05-27 10:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_reference', models.CharField(editable=False, help_text='Auto-generated unique customer ID', max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for API', unique=True)),
                ('name', models.CharField(db_index=True, help_text="Customer's full name or business name", max_length=200)),
                ('phone', models.CharField(help_text='Kenyan phone number (e.g., 0712345678)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be Kenyan format: 0712345678 or +254712345678', regex='^(\\+254|0)[17]\\d{8}$')])),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, unique=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('tax_number', models.CharField(blank=True, help_text='KRA PIN for VAT purposes', max_length=50, null=True)),
                ('loyalty_records', models.IntegerField(default=0, help_text='Accumulated loyalty points', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lifetime spending total', max_digits=12)),
                ('pricing_tier', models.CharField(choices=[('retail', 'Retail Customer'), ('wholesale', 'Wholesale Customer'), ('vip', 'VIP Customer')], default='retail', help_text='Determines which price tier applies', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive customers cannot make purchases')),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Blacklisted customers are blocked from sales')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['account_reference'], name='customers_c_account_76fb92_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'), models.Index(fields=['pricing_tier'], name='customers_c_pricing_1fa296_idx'), models.Index(fields=['last_purchase_date'], name='customers_c_last_pu_dfc1e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='loyalty_points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='customers.customer')),
            ],
        ),
    ]
