# Generated by Django 6.0.5 on 2026-05-27 10:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public identifier for API', unique=True)),
                ('phone', models.CharField(help_text='Kenyan phone number', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be Kenyan format: 0712345678 or +254712345678', regex='^(\\+254|0)[17]\\d{8}$')])),
                ('employee_id', models.CharField(blank=True, help_text='Company employee ID', max_length=20, null=True, unique=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('casual', 'Casual')], default='full_time', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('inventory_clerk', 'Inventory Clerk'), ('viewer', 'Viewer')], default='cashier', help_text="User's role determines permissions", max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary in KES', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission percentage on sales (0-100)', max_digits=5)),
                ('default_shift', models.CharField(choices=[('morning', 'Morning (6AM - 2PM)'), ('afternoon', 'Afternoon (2PM - 10PM)'), ('night', 'Night (10PM - 6AM)'), ('flexible', 'Flexible')], default='morning', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot log in')),
                ('is_online', models.BooleanField(default=False, help_text='Currently logged in')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'), models.Index(fields=['employee_id'], name='users_employe_55e465_idx'), models.Index(fields=['phone'], name='users_phone_af6883_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
